#!/bin/sh

# Remove /system-update first, to avoid reboot loops.
/usr/bin/rm -fv /system-update

# Perform the system update using Pacman.
/usr/bin/pacman -Su --noconfirm --color=auto > /dev/tty1 2>&1

# Reboot the system.
/usr/bin/systemctl reboot
